//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaPadaria.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgramaPadaria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1769523054083 {
            get {
                object obj = ResourceManager.GetObject("1769523054083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7783093 {
            get {
                object obj = ResourceManager.GetObject("7783093", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7db99d46d3568fe5b985e529b133cddb_icone_da_lupa_do_olho__1_ {
            get {
                object obj = ResourceManager.GetObject("7db99d46d3568fe5b985e529b133cddb-icone-da-lupa-do-olho (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__10_41_41 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar. de 2026, 10_41_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__10_52_56 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar. de 2026, 10_52_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__11_32_56 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar. de 2026, 11_32_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__11_32_56_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ChatGPT_Image_12_de_mar._de_2026__11_32_56-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__11_36_48 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar. de 2026, 11_36_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__11_36_48_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ChatGPT_Image_12_de_mar._de_2026__11_36_48-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar__de_2026__11_36_48_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT_Image_12_de_mar._de_2026__11_36_48-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar1 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_mar2 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de mar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_13_de_mar__de_2026__10_23_37 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 13 de mar. de 2026, 10_23_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dramatic_abstract_bundle_of_wheat_stalks_professional_png {
            get {
                object obj = ResourceManager.GetObject("dramatic-abstract-bundle-of-wheat-stalks-professional-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dramatic_abstract_bundle_of_wheat_stalks_professional_png1 {
            get {
                object obj = ResourceManager.GetObject("dramatic-abstract-bundle-of-wheat-stalks-professional-png1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dramatic_abstract_bundle_of_wheat_stalks_professional_png2 {
            get {
                object obj = ResourceManager.GetObject("dramatic-abstract-bundle-of-wheat-stalks-professional-png2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000391871f5a5809e0fc6e67c84 {
            get {
                object obj = ResourceManager.GetObject("file_00000000391871f5a5809e0fc6e67c84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_5gdyde5gdyde5gdy {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_5gdyde5gdyde5gdy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_5gdyde5gdyde5gdy1 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_5gdyde5gdyde5gdy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_9lapyq9lapyq9lap {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_9lapyq9lapyq9lap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_an6e4lan6e4lan6e {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_an6e4lan6e4lan6e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_bjpvfxbjpvfxbjpv {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_bjpvfxbjpvfxbjpv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_cto8z7cto8z7cto8 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_cto8z7cto8z7cto8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_fvujj1fvujj1fvuj {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_fvujj1fvujj1fvuj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_fvujj1fvujj1fvuj_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_fvujj1fvujj1fvuj-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_xgk5erxgk5erxgk5 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_xgk5erxgk5erxgk5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_xgk5erxgk5erxgk5_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_xgk5erxgk5erxgk5-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_money_bag_dollar_3d_illustration_png {
            get {
                object obj = ResourceManager.GetObject("green-money-bag-dollar-3d-illustration-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap impressive_classic_freshly_baked_bread_loaf_isolated_rustic_style_4k_free_png {
            get {
                object obj = ResourceManager.GetObject("impressive-classic-freshly-baked-bread-loaf-isolated-rustic-style-4k-free-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_among_ears_the_peace_of_wheat_fields_png_image_12725035_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-among-ears-the-peace-of-wheat-fields-png-image_12725035-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quadro_degrade_laranja_marrom_arte_canvas_moldura_90x140_arte_em_tons_de_marrom {
            get {
                object obj = ResourceManager.GetObject("quadro-degrade-laranja-marrom-arte-canvas-moldura-90x140-arte-em-tons-de-marrom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap realistic_correct_checkmark_symbol_yes_right_and_approved_icon_3d_render_illustration_free_png {
            get {
                object obj = ResourceManager.GetObject("realistic-correct-checkmark-symbol-yes-right-and-approved-icon-3d-render-illustra" +
                        "tion-free-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ripe_wheat_stalks_harvest_wheat_ears_isolated_on_transparent_background_free_png_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ripe-wheat-stalks-harvest-wheat-ears-isolated-on-transparent-background-free-png-" +
                        "removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stunning_traditional_bundle_of_wheat_stalks_genuine_png {
            get {
                object obj = ResourceManager.GetObject("stunning-traditional-bundle-of-wheat-stalks-genuine-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stunning_traditional_bundle_of_wheat_stalks_genuine_png_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("stunning-traditional-bundle-of-wheat-stalks-genuine-png-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stunning_traditional_bundle_of_wheat_stalks_genuine_png_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("stunning-traditional-bundle-of-wheat-stalks-genuine-png-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textura_sem_costura_de_vetor_xadrez_padrao_rosa_na_caixa_backgraund_quadriculado_629110_130 {
            get {
                object obj = ResourceManager.GetObject("textura-sem-costura-de-vetor-xadrez-padrao-rosa-na-caixa-backgraund-quadriculado_" +
                        "629110-130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap todo_list_icon_notepad_with_completed_todo_list_and_pencil_3d_render_png {
            get {
                object obj = ResourceManager.GetObject("todo-list-icon-notepad-with-completed-todo-list-and-pencil-3d-render-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_web_button_png {
            get {
                object obj = ResourceManager.GetObject("yellow-web-button-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_web_button_png1 {
            get {
                object obj = ResourceManager.GetObject("yellow-web-button-png1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
